#!/bin/bash

set -u

usage() {
    echo "${0/*\/} --tftpserver <tftpserver> --tftproot <tftproot> --tftppath <tftppath> --tsv <host[,access,enable]> --commit-message \"<message>\""
}

if [ $# -eq 0 ]; then
    usage 1>&2 ;
    exit 1;
fi

while (( $# )) ; do
    case $1 in
        --tftpserver )
                tftpserver=$2;
                shift;shift;;
        --tftproot )
                tftproot=$2;
                shift;shift;;
        --tftppath )
                tftppath=$2;
                shift;shift;;
        --tsv )
                tsv=$2;
                shift;shift;;
        --commit-message )
                commitmessage=$2
                shift;shift;;
       * )
                echo "Unrecognized option $1" 1>&2 ;
                usage 1>&2 ;
                exit 2 ;;
    esac
done

if [ -z "$tftpserver" ]; then echo "missing tftpserver"; exit 3; fi
if [ -z "$tftproot" ]; then echo "missing tftproot"; exit 3; fi
if [ -z "$tftppath" ]; then echo "missing tftppath"; exit 3; fi
if [ -z "$tsv" ]; then echo "missing tsv"; exit 3; fi
if [ -z "$commitmessage" ]; then echo "missing commitmessage"; exit 3; fi

while read -r device access enable; do
        if [[ $device =~ '#' ]] ; then
                continue
                echo $device
        fi
        latest=$(ls -1tr $tftproot/$tftppath/$device* | tail -n1);
        while [ $(wc -c <"$latest") -eq 65536 ]; do
                config-backup --tftpserver $tftpserver --tftproot $tftproot --tftppath $tftppath --tsv <(grep $device $tsv)
                latest=$(ls -1tr $tftproot/$tftppath/$device* | tail -n1);
        done
        ln -f $latest $tftproot/${tftppath/${tftppath/*\/}}/current/${tftppath/${tftppath/\/*}}/$device.cfg;
done < $tsv

cd $tftproot/${tftppath/${tftppath/*\/}}/current/
git commit -a -m $commitmessage | grep -v -e '# On branch main' -e 'nothing to commit, working directory clean'
[ $? -eq 0 ] && git push --quiet | grep -v 'Everything up-to-date'
